### ISSUE TITLE
[3.6.6] Cat refuses to move out of a 2x2 corner of a room

### ISSUE THREAD

**Issue by Pwntheon** [NetHack/NetHack#790] opened 2022-06-05 06:16 UTC
This is a strange bug. I just started as a wizard, and on one of the upper floors, my cat flatly refuses to leave a room. It insists on staying within the 2x2 square at the bottom right. 

![image](https://user-images.githubusercontent.com/1849517/172037925-21983a01-8d44-4346-af00-f675f736c343.png)

It's not surrounded by traps/cursed items. It purrs when i chat it up. It will attack enemies if i lead them to her. I can displace her out of her "home" but she returns there immediately after. I'm not invisible.

Just before this, there was a brown mold in the middle of this room which the cat attacked twice, before refusing to go near it again. I killed it myself thinking it was afraid of the mold, but even with the mold and the corpse gone, the cat refuses to get out of it's corner.

Attached is the save file.

[Pantheon.zip](https://github.com/NetHack/NetHack/files/8839419/Pantheon.zip)

**Comment by ostrosablin** [comment] 2022-06-05 07:46
This is a duplicate of issue #329 . Annoying as hell (and one of reasons why I've moved to unstable 3.7 version).

https://github.com/NetHack/NetHack/issues/329#issuecomment-683310082

Basically, there's a monster in a closet behind the iron bars. You can't see it, because it's dark there, but pet knows it's there and is "locked on" it to attack. But it cannot reach it there, so it basically gets stuck.

Same problem occurs in shops, where unrevealed mimics are present - pet knows that mimic is there, but refuses to attack it (perhaps due to being not leveled enough), but it's still "locked on" mimic, so it just waits indefinitely.

**Comment by nhmall** [comment] 2022-06-05 13:27
This would be a NetHack 3.6.6 variation of the patch from @copperwater for issue #329, that has already been applied to NetHack-3.7 work-in-progress. If you're able to build from source, perhaps it will be of use to you.
```
diff --git a/src/dogmove.c b/src/dogmove.c
index df3452faa..b86153ec6 100644
--- a/src/dogmove.c
+++ b/src/dogmove.c
@@ -1148,11 +1148,17 @@ int after; /* this is extra fast monster movement */
 
         /* Hungry pets are unlikely to use breath/spit attacks */
         if (mtarg && (!hungry || !rn2(5))) {
-            int mstatus;
+            int mstatus = MM_MISS;
 
             if (mtarg == &youmonst) {
                 if (mattacku(mtmp))
                     return 2;
+                /* Treat this as the pet having initiated an attack even if it
+                 * didn't, so it will lose its move. This isn't entirely fair,
+                 * but mattacku doesn't distinguish between "did not attack" and
+                 * "attacked but didn't die" cases, and this is preferable to
+                 * letting the pet attack the player and continuing to move */
+                mstatus = MM_HIT;
             } else {
                 mstatus = mattackm(mtmp, mtarg);
 
@@ -1179,6 +1185,18 @@ int after; /* this is extra fast monster movement */
                     }
                 }
             }
+            /* Only return 3 if the pet actually made a ranged attack, and thus
+             * should lose the rest of its move.
+             * There's a chain of assumptions here:
+             * 1. score_targ and best_target will never select a monster that
+             *    can be attacked in melee, so the mattackm call can only ever
+             *    try ranged options
+             * 2. if the only attacks available to mattackm are ranged options,
+             *    and the monster cannot make a ranged attack, it will return
+             *    MM_MISS.
+             */
+            if (mstatus != MM_MISS)
+                return 3;
         }
     }
 
diff --git a/src/mhitm.c b/src/mhitm.c
index 5ebbd8429..d8b8aab04 100644
--- a/src/mhitm.c
+++ b/src/mhitm.c
@@ -360,6 +360,9 @@ register struct monst *magr, *mdef;
             if (distmin(magr->mx, magr->my, mdef->mx, mdef->my) > 1) {
                 /* D: Do a ranged attack here! */
                 strike = thrwmm(magr, mdef);
+                if (strike)
+                    /* We don't really know if we hit or not; pretend we did. */
+                    res[i] |= MM_HIT;
                 if (DEADMONSTER(mdef))
                     res[i] = MM_DEF_DIED;
                 if (DEADMONSTER(magr))

```

**Closed as completed** 2022-06-07 17:30 UTC
Labels: 3.6
