### ISSUE TITLE
Extra num_args++ increments in winmisc.c

### ISSUE THREAD

**Issue by TonyCrawford** [NetHack/NetHack#658] opened 2022-01-19 14:36 UTC
Haven't seen any trouble from this yet, but it's not clean. Somebody was in the flow with their num_args++ and forgot it's a separate statement.
```
diff --git a/win/X11/winmisc.c b/win/X11/winmisc.c
index 23404715f..17f366ba4 100644
--- a/win/X11/winmisc.c
+++ b/win/X11/winmisc.c
@@ -921,13 +921,15 @@ X11_player_selection_dialog(void)
         Widget racewidget;
 
         num_args = 0;
-        if (i > 0)
+        if (i > 0) {
             XtSetArg(args[num_args], nhStr(XtNfromVert),
                      tmpwidget); num_args++;
+        }
         XtSetArg(args[num_args], XtNwidth, cwid); num_args++;
-        if (i > 0)
+        if (i > 0) {
             XtSetArg(args[num_args], nhStr(XtNradioGroup),
                      plsel_race_radios[0]); num_args++;
+        }
         XtSetArg(args[num_args], nhStr(XtNradioData), (i + 1)); num_args++;
 
         racewidget = XtCreateManagedWidget(races[i].noun,
@@ -983,13 +985,15 @@ X11_player_selection_dialog(void)
         Widget rolewidget;
 
         num_args = 0;
-        if (i > 0)
+        if (i > 0) {
             XtSetArg(args[num_args], nhStr(XtNfromVert),
                      tmpwidget); num_args++;
+        }
         XtSetArg(args[num_args], nhStr(XtNwidth), cwid); num_args++;
-        if (i > 0)
+        if (i > 0) {
             XtSetArg(args[num_args], nhStr(XtNradioGroup),
                      plsel_role_radios[0]); num_args++;
+        }
         XtSetArg(args[num_args], nhStr(XtNradioData), (i + 1)); num_args++;
 
         rolewidget = XtCreateManagedWidget(roles[i].name.m, toggleWidgetClass,
```

**Comment by nhmall** [comment] 2022-01-19 15:44
I think someone fixed some of those in 415cfd808c5cea58ec3d42c443799e2b6fd6709f, but possibly only the ones that a compiler griped about.

**Comment by TonyCrawford** [comment] 2022-01-19 17:10
That would be one smart compiler. Oh -- requiring a block after every if? That would be a lot of gripes.

**Comment by nhmall** [comment] 2022-01-19 19:37
Below is a sample of the set of warnings which, once reported, led to the discovery of the original issue and 415cfd808c5cea58ec3d42c443799e2b6fd6709f

`gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0`

`cc -g -I../include -DNOTPARMDECL -Wall -Wextra -Wno-missing-field-initializers -Wreturn-type -Wunused -Wformat -Wswitch -Wshadow -Wwrite-strings -pedantic -Wmissing-declarations -Wunreachable-code -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -Wmissing-parameter-type -Wformat-overflow -DGCC_WARN -DNOTTYGRAPHICS -DX11_GRAPHICS        -DDLB -DHACKDIR=\"/home/testuser/nh/install/games/lib/nethackdir\" -DDEFAULT_WINDOW_SYS=\"X11\" -DSYSCF -DSYSCF_FILE=\"/home/testuser/nh/install/games/lib/nethackdir/sysconf\" -DSECURE -DTIMED_DELAY -DDUMPLOG -DCONFIG_ERROR_SECURE=FALSE -DCOMPRESS=\"/bin/gzip\" -DCOMPRESS_EXTENSION=\".gz\" -DUSE_XPM -I/opt/X11/include -Wno-variadic-macros -c -o winstat.o ../win/X11/winstat.c`
```
../win/X11/winstat.c: In function ‘create_tty_status_field’:
../win/X11/winstat.c:945:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  945 |     if (above)
      |     ^~
../win/X11/winstat.c:946:62: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  946 |         XtSetArg(args[num_args], nhStr(XtNfromVert), above); num_args++;
      |                                                              ^~~~~~~~
../win/X11/winstat.c:947:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  947 |     if (left)
      |     ^~
../win/X11/winstat.c:948:62: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  948 |         XtSetArg(args[num_args], nhStr(XtNfromHoriz), left); num_args++;
      |                                                              ^~~~~~~~
../win/X11/winstat.c: In function ‘create_tty_status’:
../win/X11/winstat.c:980:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  980 |     if (top)
      |     ^~
../win/X11/winstat.c:981:60: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  981 |         XtSetArg(args[num_args], nhStr(XtNfromVert), top); num_args++;
      |                                                            ^~~~~~~~
```


EDIT: Attempt to format it a little better.

**Comment by nhmall** [comment] 2022-01-19 21:02
Changes committed in 30af8e0ddc7950d59df0f05f0e0bb1e9c4e9e0db.

It's too bad that the compiler was not able to catch the occurrences in winmisc.c, but was able to catch the occurrences in winstat.c. It makes me wonder why that's the case. Perhaps it's because the XtSetArg() parameters were wrapped to a new line in winmisc.c for line-length reasons.   I have not confirmed that.

**Comment by TonyCrawford** [comment] 2022-01-19 22:11
If num_args++ were preceded by a comma instead of a semicolon, the two statements would be one, and no braces or "misleading indentation" warnings (in a language in which whitespace merely divides tokens) would be necessary.

**Comment by nhmall** [comment] 2022-01-19 22:15
yep. @pat-rankin also noted that in his commit message for 415cfd808c5cea58ec3d42c443799e2b6fd6709f

**Comment by pat-rankin** [comment] 2022-01-19 23:20
> If num_args++ were preceded by a comma instead of a semicolon

Unfortunately that won't work here, because XtSetArg() is a macro
which expands to an expression enclosed by curly braces, so when
 XtSetArg(foo), bar++;
became
 { something involving foo }, bar++;
it would be rejected.

**Closed as completed** 2022-01-20 01:34 UTC
