### ISSUE TITLE
Poor Menu Heading Visibility in curses Mode

### ISSUE THREAD

**Issue by jlamothe** [NetHack/NetHack#480] opened 2021-03-31 15:42 UTC
When running 3.6.6 in curses mode, headings appear to render in a very dark colour on a black background, making them very difficult to read. Setting `OPTIONS=menu_headings:normal` in the config file makes the headings in the inventory menu legible, but has no effect on the dungeon overview headings.

**Comment by ostrosablin** [comment] 2021-03-31 17:18
Can you provide a screenshot, please?

I don't remember seeing anything like you have described in curses windowport, so I would assume that problem isn't a NetHack issue.

Most likely, it's a terminal configuration issue. There's a problem with various terminal colour schemes, when some elements appear poorly-colored and either not visible at all or are difficult to read. This is because many color schemes are designed for displaying texts, and since NetHack uses extensive display/color capabilities, this causes color scheme to exhibit weird colors in some corner cases, where background and foreground colors are not contrasting enough to be readable.

Particularly, I remember having an issue with Solarized color scheme, where OPTIONS=dark_room doesn't display properly (making no difference). Because of that, I have to fallback to default Linux terminal color scheme for playing NetHack.

Unfortunately, there's not much that can be done about this on NetHack's side. NetHack doesn't know anything about underlying terminal's color scheme, because terminal essentially substitutes colors that NetHack to colors specified by color scheme.

So, if that's the case - there's only two options.

1. Either change your terminal's color scheme to a different color scheme, which doesn't exhibit issue (Linux colors is a safe bet - all colors should be visible and readable).
2. If your terminal supports manually editing the color schemes - it might be viable to just tune your current color scheme and reassign problematic colors, so that they're more contrasting.

If this is not helpful, you can check out following NetHackWiki page for other possible workarounds for color issues.

https://nethackwiki.com/wiki/Colors

**Comment by jlamothe** [comment] 2021-03-31 18:12
Here's how the menus are showing for me: https://imgur.com/a/x6oRUkh

For context, this is NetHack 3.6.6 being run on nethack.alt.org in the default terminal emulator for Ubuntu 20.04.

This issue is only present when I run it in curses mode. I've made the following changes to the default config file:
enabling curses (obviously)
enabling DECgraphics
enabling hilite_pet and hilite_pile

I've also included a shot of how the inventory menu looks like when I set `OPTIONS=menu_headings:normal`. This setting has no effect on the dungeon overview menu.

When curses is not enabled, everything works as one would expect.

**Comment by ostrosablin** [comment] 2021-03-31 19:41
Yes, you're right. Some menu headings indeed appear to use a weird combinations of background/foreground colors, which are identical in most color schemes. I believe correct appearance of menu headers is how it's done in `OPTIONS=perm_invent` window in curses mode.

And `OPTIONS=menu_headings:normal` not applying to dungeon overview menu also seems to be a separate overlooked bug.

You can try changing color scheme in terminal as documented here as a workaround.

https://linuxhint.com/ubuntu_terminal_color_scheme/

I believe this is closest to how it's supposed to look like (under Konsole terminal emulator + "Linux Colors" color scheme). Note that while heading text is indeed dark, it's still readable.

![image](https://user-images.githubusercontent.com/5955408/113199531-e707b800-926f-11eb-8b30-190262e7326a.png)

However, setting the color scheme to pretty much anything else renders menu headers non-readable (here's example with "Solarized Dark" scheme).

![image](https://user-images.githubusercontent.com/5955408/113200429-f9cebc80-9270-11eb-86e7-13fac60ebc5b.png)

I believe, headers in the menu are displayed with bright background color, while text is displayed in color 1, which in most color schemes is same color (or very close), rendering text either poorly readable, or not visible outright.

**Comment by ostrosablin** [comment] 2021-03-31 19:56
Here's colors defined for "Linux Colors" color scheme.

![image](https://user-images.githubusercontent.com/5955408/113201838-ac534f00-9272-11eb-8966-e237d7e37291.png)

Note that since headings are displayed in "Inverse Video", background and foreground colors are actually swapped - dark gray background color is used for text, as seen in my previous comment.

However, if we take a look in Solarized Dark color scheme:

![image](https://user-images.githubusercontent.com/5955408/113202595-9befa400-9273-11eb-9e66-5379cd949b74.png)

It's actually one and the same color: `#073642`

Same is true for most other color schemes - Color 1 and Background color are either identical, or very close, non-contrasting colors.

Also, I believe exact same problem is reason why `OPTIONS=dark_room` doesn't work in Solarized Dark color scheme - some colors are duplicate.

**Comment by FredrIQ** [comment] 2021-03-31 20:03
I've also encountered this problem. I assumed it was a termcap oddity, but it'd be nice if it could be fixed. It only appears in regular curses menus -- the perm_invent window doesn't manifest this problem, and I've also only started to have this problem somewhat recently, which is why I chalked it up to termcap confusion.

I am the original author of the perm_invent capabilities in curses, and I wasn't sure if I should adjust the other curses menus to work in a similar way to avoid this problem. Hence why I've left it alone.

**Comment by ostrosablin** [comment] 2021-03-31 20:28
Here's an example of customized Solarized Dark theme.

![image](https://user-images.githubusercontent.com/5955408/113205107-95166080-9276-11eb-9bbb-6ceed8aa5671.png)

I've changed only "color 1" here. Set it to something different than background-like colors.

And here's results. Also, suddenly, "dark_room" option shows distinguishable colors.

![image](https://user-images.githubusercontent.com/5955408/113205354-e0c90a00-9276-11eb-8442-d8fc9a36fef9.png)

Note that left inventory window (I menu) and right (perm_invent) have differently colored headings - that's because left window use Color 1 + Bright Background for headings. And perm_invent uses Text + Background colors. Which is I believe the correct way to implement a menu heading, because text and background colors are guaranteed to be contrasting and readable one over another in any sane color scheme.

Other menu headings make assumptions that Bright Background should be indeed "bright" and normal Color 1 is dark and contrasting enough, which appears to be not true for most pre-installed color schemes for Konsole terminal emulator.

Also, Color 1 appears to be used for dark_room feature, which is not limited to curses-only, but also for tty. And since dark areas of room are displayed in Color 1 - it blends in with background in many color schemes, rendering dots invisible (only "Linux Colors" scheme works more or less as intended, but headings are still messed up, since they should be inverse video, but instead appear dark-gray-on-black)

**Comment by bhaak** [comment] 2021-04-01 08:44
@FredrIQ  it's a type error. The menu headings supply the NO_COLOR constant of the NetHack internal color structures instead of the NONE constant for curses.

NO_COLOR is 8 and that gets interpreted in curses_toggle_color_attr() as color pair index + 1 and that is dark gray. The menu headings are supposed to be colored in the foreground/text color. Depending on your color scheme it's not obvious that they are drawn in a different color.

I'd say perm inventory headings should behave the same as the menu headings in the inventory window. Right now, they are also not subject the menucolors.

I'll fix that later today.

**Comment by ostrosablin** [comment] 2021-04-01 10:22
Actually, here's the reason why `OPTIONS=menu_headings:normal` applies only for inventory menu and not Dungeon Overview menu.

https://github.com/NetHack/NetHack/blob/cc25f40d69ec54d6b18f155a027be563f57c5a04/src/dungeon.c#L3260

This is not related to curses at all, same happens on tty. It's because Dungeon Overview currently is exempt from menu_headings system. It just puts ATR_INVERSE directly into branch lines.

**Closed as completed** 2021-04-02 02:37 UTC
