### ISSUE TITLE
Jumping onto a square containing a pit yields odd message

### ISSUE THREAD

**Issue by sobjornstad** [NetHack/NetHack#115] opened 2018-07-07 15:57 UTC
Jumping into a pit, even from just one square away, yields the message, “You pass right over a (spiked) pit.  You fall into a pit!” (Alternatively, if you escape it, “You pass right over a pit. You escape a pit.”)

**Comment by nhmall** [comment] 2018-09-05 23:32
What version is this in?  I couldn't reproduce it with the information above in the current post-3.6.1  NetHack-3.6.2-beta01 branch code. There was some pit related changes committed in April, e48600ec87616112f59b2562a2fe3f3c22e5d3bb  and 56ceea5a41a3eaa51dcad21ef9271a181093f293

**Comment by sobjornstad** [comment] 2018-10-12 22:14
Sorry for the delay here! This was in 3.6.1 on NAO. I wouldn't be surprised if one of those commits fixed it.

**Comment by nhmall** [comment] 2018-10-14 16:57
Resolving. If it wasn’t the previously mentioned commits, there’s this one 
37f8d0edb3826c7e845f79566b54845fd1c2f6a4

**Closed as completed by nhmall** 2018-10-14 16:57 UTC
